default_context:
  project_name: 'BudgetCars'
  project_slug: 'budgetcars'
  domain_main: 'budgetcars.com'
  domain_staging: 'stag.budgetcars.com'
  docker_swarm_stack_name_main: 'budgetcars-com'
  docker_swarm_stack_name_staging: 'stag-budgetcars-com'
  secret_key: 'bc493bfadcfbc143a8b9d425a94de6835badb3ad904f6bcfbbf2da58119ab6f7'
  first_superuser: 'admin@budgetcars.com'
  first_superuser_password: 'Password1'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.budgetcars.com", "https://stag.budgetcars.com", "https://budgetcars.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@budgetcars.com'
  postgres_password: 'pass'
  pgadmin_default_user: 'user'
  pgadmin_default_user_password: 'Password1'
  traefik_constraint_tag: 'budgetcars.com'
  traefik_constraint_tag_staging: 'stag.budgetcars.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Password1'
  sentry_dsn: 'https://1234abcd:5678ef@sentry.example.com/30'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
