"""Add car table

Revision ID: 695a1b7fbd81
Revises: b7b17f658201
Create Date: 2023-07-21 11:56:20.366469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695a1b7fbd81'
down_revision = 'b7b17f658201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('kilometers', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'UNKNOWN', name='fueltype'), nullable=False),
    sa.Column('transmission', sa.Enum('MANUAL', 'AUTOMATIC', 'UNKNOWN', name='transmission'), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_color'), 'cars', ['color'], unique=False)
    op.create_index(op.f('ix_cars_fuel_type'), 'cars', ['fuel_type'], unique=False)
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_kilometers'), 'cars', ['kilometers'], unique=False)
    op.create_index(op.f('ix_cars_make'), 'cars', ['make'], unique=False)
    op.create_index(op.f('ix_cars_model'), 'cars', ['model'], unique=False)
    op.create_index(op.f('ix_cars_price'), 'cars', ['price'], unique=False)
    op.create_index(op.f('ix_cars_seats'), 'cars', ['seats'], unique=False)
    op.create_index(op.f('ix_cars_transmission'), 'cars', ['transmission'], unique=False)
    op.create_index(op.f('ix_cars_year'), 'cars', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_year'), table_name='cars')
    op.drop_index(op.f('ix_cars_transmission'), table_name='cars')
    op.drop_index(op.f('ix_cars_seats'), table_name='cars')
    op.drop_index(op.f('ix_cars_price'), table_name='cars')
    op.drop_index(op.f('ix_cars_model'), table_name='cars')
    op.drop_index(op.f('ix_cars_make'), table_name='cars')
    op.drop_index(op.f('ix_cars_kilometers'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_fuel_type'), table_name='cars')
    op.drop_index(op.f('ix_cars_color'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
